# POST /api/users/register
POST http://localhost:4000/api/users/register
Content-Type: application/json

{
  "name": "siyaramsir",
  "email": "siyaramsir@example.com",
  "password": "siyaramsir",
  "confirmPassword": "siyaramsir",
  "mobile": "1234567890"
}

//this api is for all the users
###
GET http://localhost:4000/api/users


//Delete user 
# DELETE /api/users/:id
###
DELETE http://localhost:4000/api/users/665c2c0da4fadcd9bff8c032

###
# POST /api/users/login
POST http://localhost:4000/api/users/login
Content-Type: application/json

{
  "email": "siyaramsir@example.com",
  "password": "siyaramsir"
}


//update the user details

# PUT /api/users/:id
###
PUT http://localhost:4000/api/users/665b776f52224e14e6d97b19
Content-Type: application/json

{
  "name": "amit yadav",
  "email": "amit@example.com",
  "password": "newpassword",
  "mobile": "987654321r",
  "profileImage": "/uploads/newprofile.jpg",
  "address": "punjab",
  "bio": "he is a good boy"
}



//admin register 

# POST /api/admin/register
###
POST http://localhost:4000/api/admin/register
Content-Type: application/json

{
  "name": "amit",
  "email": "sdfsd@gmail.com",
  "password": "adminPassword",
  "mobile": "1234567890"
}


//get all admins
###
GET http://localhost:4000/api/admin

//delete user authority

# DELETE /api/admin/admin/:id
###
DELETE http://localhost:4000/api/admin/users/6654ce72a11c10cc02011024



//update admin details

# PUT /api/users/:id
###

PUT http://localhost:4000/api/admin/admins/6654d082e0fd4248f6d98b1e
Content-Type: application/json

{
  "name": "amitabh",
  "email": "amitabh@example.com",
  "password": "newpassword",
  "mobile": "9876543214",
  "profileImage": "/uploads/newprofile.jpg",
  "address": "punjab",
  "bio": "Amitabh bachan is a very great actor of India.thay give 100+ films"
}


// for the quesiton 
###
POST http://localhost:4000/api/questions
Content-Type: application/json

{
  "subjectName": "javascript",
  "quizSet": "set3",
  "question": "Which CSS property is used to align text?",
  "options": [
    "text-align",
    "color",
    "background-color",
    "font-size"
  ],
  "answer": "text-align"
}


//get questions

###
GET http://localhost:4000/api/questions/html/set2


# GET http://localhost:4000/api/questions/:subjectName/:quizSet

### Save Quiz Result
POST http://localhost:4000/api/quizResults
Content-Type: application/json

{
  "userId": "665f4f1f9e43e4eb8ea52551",
  "subjectName": "css",
  "quizSet": "set3",
  "totalQuestions": 10,
  "wrongAnswers": 2,
  "correctAnswers": 8,
  "resultMessage": "Good job!",
  "percentageScore": 80,
  "dateTime": "2024-06-03T10:00:00Z",
  "name": "John Doe",
  "email": "johndoe@example.com"
}

###
GET http://localhost:4000/api/quizResults

###
GET http://localhost:4000/api/quizResults/html/Set1


# Get All Quiz Results for a User
###
2GET http://localhost:4000/api/quizResults?userId=665f4f1f9e43e4eb8ea52551


#Get Quiz Results by Subject and Set for a User
###
http://localhost:4000/api/quizResults/html/set1?userId=665f4f1f9e43e4eb8ea52551



//for the delete quiz history sir
// http://localhost:3000/quiz-results?userId=123&subjectName=math&quizSet=set1
###
DELETE http://localhost:4000/api/quizResults?userId=665f4f1f9e43e4eb8ea52551&subjectName=html&quizSet=set1

