# POST /api/users/register
POST http://localhost:4000/api/users/register
Content-Type: application/json

{
  "name": "mohan Doe",
  "email": "sohan@example.com",
  "password": "password123",
  "confirmPassword": "password123",
  "address": "123 Main St",
  "mobile": "1234567890"
}

//this api is for all the users
###
GET http://localhost:4000/api/users


//Delete user 
# DELETE /api/users/:id
###
DELETE http://localhost:4000/api/users/665b778652224e14e6d97b1c

###
# POST /api/users/login
POST http://localhost:4000/api/users/login
Content-Type: application/json

{
  "email": "mohan@example.com",
  "password": "password123"
}


//update the user details

# PUT /api/users/:id
###
PUT http://localhost:4000/api/users/665b776f52224e14e6d97b19
Content-Type: application/json

{
  "name": "amit yadav",
  "email": "amit@example.com",
  "password": "newpassword",
  "mobile": "987654321r",
  "profileImage": "/uploads/newprofile.jpg",
  "address": "punjab",
  "bio": "he is a good boy"
}



//admin register 

# POST /api/admin/register
###
POST http://localhost:4000/api/admin/register
Content-Type: application/json

{
  "name": "amit",
  "email": "mohan@gmail.com",
  "password": "adminPassword",
  "mobile": "1234567890"
}


//get all admins
###
GET http://localhost:4000/api/admin

//delete user authority

# DELETE /api/admin/admin/:id
###
DELETE http://localhost:4000/api/admin/users/6654ce72a11c10cc02011024



//update admin details

# PUT /api/users/:id
###

PUT http://localhost:4000/api/admin/admins/6654d082e0fd4248f6d98b1e
Content-Type: application/json

{
  "name": "amitabh",
  "email": "amitabh@example.com",
  "password": "newpassword",
  "mobile": "9876543214",
  "profileImage": "/uploads/newprofile.jpg",
  "address": "punjab",
  "bio": "Amitabh bachan is a very great actor of India.thay give 100+ films"
}


// for the quesiton 
###
POST http://localhost:4000/api/questions
Content-Type: application/json

{
  "subjectName": "css",
  "quizSet": "set4",
  "question": "Which CSS property is used to align text?",
  "options": [
    "text-align",
    "color",
    "background-color",
    "font-size"
  ],
  "answer": "text-align"
}


//get questions

###
GET http://localhost:4000/api/questions/css/set1


# GET http://localhost:4000/api/questions/:subjectName/:quizSet


### Save Quiz History
POST http://localhost:4000/api/quiz-history
Content-Type: application/json

{
  "userId": "665b776f52224e14e6d97b19",  
  "subjectName": "CSS",
  "quizSet": "set3",
  "totalQuestions": "5",
  "correctAnswers": "3",
  "wrongAnswers": "2",
  "percentageScore":" 60.00",
  "resultMessage": "Congratulations! You did very well.",
  "dateTime": "2024-06-01T22:56:36.000Z",
  "name": "rajesh",
  "email": "rajesh@gmail.com"
}